export const DUMMY_DATA = [
  {
    bodyPart: "chest",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1254.gif",
    id: "1254",
    name: "band bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0025.gif",
    id: "0025",
    name: "barbell bench press",
    target: "pectorals",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0030.gif",
    id: "0030",
    name: "barbell close-grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0033.gif",
    id: "0033",
    name: "barbell decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0045.gif",
    id: "0045",
    name: "barbell guillotine bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0047.gif",
    id: "0047",
    name: "barbell incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1719.gif",
    id: "1719",
    name: "barbell incline close grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0052.gif",
    id: "0052",
    name: "barbell jm bench press",
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2187.gif",
    id: "2187",
    name: "barbell reverse close-grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1256.gif",
    id: "1256",
    name: "barbell reverse grip decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1257.gif",
    id: "1257",
    name: "barbell reverse grip incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0122.gif",
    id: "0122",
    name: "barbell wide bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1258.gif",
    id: "1258",
    name: "barbell wide reverse grip bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0151.gif",
    id: "0151",
    name: "cable bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0169.gif",
    id: "0169",
    name: "cable incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0289.gif",
    id: "0289",
    name: "dumbbell bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0301.gif",
    id: "0301",
    name: "dumbbell decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0314.gif",
    id: "0314",
    name: "dumbbell incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "upper arms",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0352.gif",
    id: "0352",
    name: "dumbbell neutral grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1623.gif",
    id: "1623",
    name: "dumbbell palms in incline bench press",
    target: "triceps",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1624.gif",
    id: "1624",
    name: "dumbbell reverse bench press",
    target: "pectorals",
  },
  {
    bodyPart: "upper arms",
    equipment: "dumbbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1743.gif",
    id: "1743",
    name: "dumbbell twisting bench press",
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "ez barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0450.gif",
    id: "0450",
    name: "ez barbell jm bench press",
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "ez barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2432.gif",
    id: "2432",
    name: "ez-bar close-grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0748.gif",
    id: "0748",
    name: "smith bench press",
    target: "pectorals",
  },
  {
    bodyPart: "upper arms",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0751.gif",
    id: "0751",
    name: "smith close-grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0753.gif",
    id: "0753",
    name: "smith decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0757.gif",
    id: "0757",
    name: "smith incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "upper arms",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1625.gif",
    id: "1625",
    name: "smith machine decline close grip bench press",
    target: "triceps",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1626.gif",
    id: "1626",
    name: "smith machine reverse decline close grip bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1308.gif",
    id: "1308",
    name: "smith wide grip bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1309.gif",
    id: "1309",
    name: "smith wide grip decline bench press",
    target: "pectorals",
  },
];
